site_name: ネットワーク学習ノート
use_directory_urls: false

theme:
  name: material
  language: ja

nav:
  - ホーム: index.md
  - ネットワークの基本:
    - DNS: network/dns.md
    - IPv4: network/ipv4.md
    - IPv6: network/ipv6.md
    - サブネットマスク: network/subnet.md
  - プロトコル:
    - TCP/IP: network/tcp-ip.md
    - HTTP/HTTPS: network/http.md
    - FTP: network/ftp.md
    - SMTP: network/smtp.md
  - ネットワーク機器:
    - ルーター: network/router.md
    - スイッチ: network/switch.md
    - ファイアウォール: network/firewall.md
  - セキュリティ:
    - 暗号化: network/encryption.md
    - 認証: network/authentication.md
    - VPN: network/vpn.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences